const ActionType = {
  // APP
  APP_UPDATE_LANGUAGE: "APP_UPDATE_LANGUAGE",

  // TASK
  TASK_RESET_REDUCER: "TASK_RESET_REDUCER",
  TASK_RESET_TASK_DETAILS: "TASK_RESET_TASK_DETAILS",
  TASK_FETCH_ALL: "TASK_FETCH_ALL",
  TASK_FETCH_ALL_SUCCESS: "TASK_FETCH_ALL_SUCCESS",
  TASK_FETCH_ALL_FAIL: "TASK_FETCH_ALL_FAIL",
  TASK_FETCH_BY_ID: "TASK_FETCH_BY_ID",
  TASK_FETCH_BY_ID_SUCCESS: "TASK_FETCH_BY_ID_SUCCESS",
  TASK_FETCH_BY_ID_FAIL: "TASK_FETCH_BY_ID_FAIL",
  TASK_CREATE: "TASK_CREATE",
  TASK_CREATE_SUCCESS: "TASK_CREATE_SUCCESS",
  TASK_CREATE_FAIL: "TASK_CREATE_FAIL",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_UPDATE_SUCCESS: "TASK_UPDATE_SUCCESS",
  TASK_UPDATE_FAIL: "TASK_UPDATE_FAIL",
  TASK_EDIT: "TASK_EDIT",
  TASK_EDIT_SUCCESS: "TASK_EDIT_SUCCESS",
  TASK_EDIT_FAIL: "TASK_EDIT_FAIL",
  TASK_DELETE: "TASK_DELETE",
  TASK_DELETE_SUCCESS: "TASK_DELETE_SUCCESS",
  TASK_DELETE_FAIL: "TASK_DELETE_FAIL",

  // TAG
  TAG_RESET_REDUCER: "TAG_RESET_REDUCER",
  TAG_FETCH_ALL: "TAG_FETCH_ALL",
  TAG_FETCH_ALL_SUCCESS: "TAG_FETCH_ALL_SUCCESS",
  TAG_FETCH_ALL_FAIL: "TAG_FETCH_ALL_FAIL",
  TAG_CREATE: "TAG_CREATE",
  TAG_CREATE_SUCCESS: "TAG_CREATE_SUCCESS",
  TAG_CREATE_FAIL: "TAG_CREATE_FAIL",
  TAG_EDIT: "TAG_EDIT",
  TAG_EDIT_SUCCESS: "TAG_EDIT_SUCCESS",
  TAG_EDIT_FAIL: "TAG_EDIT_FAIL",
  TAG_DELETE: "TAG_DELETE",
  TAG_DELETE_SUCCESS: "TAG_DELETE_SUCCESS",
  TAG_DELETE_FAIL: "TAG_DELETE_FAIL",
};

export default ActionType;
