const fakeData = [
  {
    id: 1,
    taskName: "Task 1",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Completed",
    actions: "test",
  },
  {
    id: 2,
    taskName: "Task 2",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "low",
    status: "Progress",
    actions: "test",
  },
  {
    id: 3,
    taskName: "Task 3",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Unassigned",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 1",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Completed",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 2",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Progress",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 3",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Unassigned",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 1",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Completed",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 2",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Progress",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 3",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Unassigned",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 2",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Progress",
    actions: "test",
  },
  {
    id: 1,
    taskName: "Task 3",
    details: "Details 1",
    tags: "Tag 1",
    createdBy: "Created By 1",
    createdOn: "Date",
    assignedTo: "Name",
    priority: "high",
    status: "Unassigned",
    actions: "test",
  },
];

export const fakeTagsData = [
  {id: 1, tags: "TAG1", colour: "red"},
  {id: 2, tags: "TAG2", colour: "red"},
  {id: 3, tags: "TAG3", colour: "red"},
]

export default fakeData;